namespaceOverride: "prometheus"

grafana:
  enabled: true

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  adminPassword: DemoPerformance2022!

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"

    path: /grafana/?(.*)

  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana # this host can be localhost